CREATE TABLE IF NOT EXISTS tenants (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	business_name VARCHAR NOT NULL, 
	description TEXT, 
	api_key VARCHAR, 
	is_active BOOLEAN, 
	email VARCHAR NOT NULL, 
	supabase_user_id VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	feedback_email VARCHAR, 
	from_email VARCHAR, 
	enable_feedback_system BOOLEAN, 
	feedback_notification_enabled BOOLEAN, 
	is_super_tenant BOOLEAN, 
	can_impersonate BOOLEAN, 
	impersonating_tenant_id INTEGER, 
	discord_bot_token VARCHAR, 
	discord_application_id VARCHAR, 
	discord_enabled BOOLEAN, 
	discord_status_message VARCHAR, 
	slack_bot_token VARCHAR, 
	slack_signing_secret VARCHAR, 
	slack_app_id VARCHAR, 
	slack_client_id VARCHAR, 
	slack_client_secret VARCHAR, 
	slack_enabled BOOLEAN, 
	slack_team_id VARCHAR, 
	slack_bot_user_id VARCHAR, 
	system_prompt TEXT, 
	system_prompt_validated BOOLEAN, 
	system_prompt_updated_at DATETIME, 
	security_level VARCHAR(20), 
	allow_custom_prompts BOOLEAN, 
	security_notifications_enabled BOOLEAN, 
	primary_color VARCHAR(7), 
	secondary_color VARCHAR(7), 
	text_color VARCHAR(7), 
	background_color VARCHAR(7), 
	user_bubble_color VARCHAR(7), 
	bot_bubble_color VARCHAR(7), 
	border_color VARCHAR(7), 
	logo_image_url VARCHAR, 
	logo_text VARCHAR(10), 
	border_radius VARCHAR(10), 
	widget_position VARCHAR(20), 
	font_family VARCHAR(100), 
	custom_css TEXT, 
	branding_updated_at DATETIME, 
	branding_version INTEGER, 
	telegram_bot_token VARCHAR, 
	telegram_enabled BOOLEAN, 
	telegram_username VARCHAR, 
	telegram_webhook_url VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(impersonating_tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS pricing_plans (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	plan_type VARCHAR, 
	price_monthly NUMERIC(10, 2), 
	price_yearly NUMERIC(10, 2), 
	max_integrations INTEGER, 
	max_messages_monthly INTEGER, 
	custom_prompt_allowed BOOLEAN, 
	website_api_allowed BOOLEAN, 
	slack_allowed BOOLEAN, 
	discord_allowed BOOLEAN, 
	whatsapp_allowed BOOLEAN, 
	features TEXT, 
	is_active BOOLEAN, 
	is_addon BOOLEAN, 
	is_popular BOOLEAN, 
	display_order INTEGER, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS admins (
	id INTEGER NOT NULL, 
	username VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	hashed_password VARCHAR NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS slack_thread_memory (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	channel_id VARCHAR(50) NOT NULL, 
	thread_ts VARCHAR(50), 
	user_id VARCHAR(50) NOT NULL, 
	conversation_context TEXT, 
	user_preferences TEXT, 
	topic_summary TEXT, 
	message_count INTEGER, 
	last_activity DATETIME, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS slack_channel_context (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	channel_id VARCHAR(50) NOT NULL, 
	channel_name VARCHAR(100), 
	channel_type VARCHAR(20), 
	bot_enabled BOOLEAN, 
	thread_mode VARCHAR(20), 
	channel_topic TEXT, 
	common_questions TEXT, 
	channel_personality TEXT, 
	total_messages INTEGER, 
	active_threads INTEGER, 
	last_activity DATETIME, 
	created_at DATETIME, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL, 
	email VARCHAR, 
	username VARCHAR, 
	hashed_password VARCHAR, 
	is_active BOOLEAN, 
	is_admin BOOLEAN, 
	tenant_id INTEGER, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS tenant_credentials (
	tenant_id INTEGER NOT NULL, 
	hashed_password VARCHAR, 
	password_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (tenant_id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS tenant_password_resets (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	token VARCHAR NOT NULL, 
	created_at DATETIME, 
	expires_at DATETIME NOT NULL, 
	is_used BOOLEAN, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS faqs (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	question TEXT, 
	answer TEXT, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS chat_sessions (
	id INTEGER NOT NULL, 
	session_id VARCHAR, 
	tenant_id INTEGER, 
	user_identifier VARCHAR, 
	language_code VARCHAR(10), 
	is_active BOOLEAN, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME, 
	user_email VARCHAR, 
	email_captured_at DATETIME, 
	email_expires_at DATETIME, 
	discord_channel_id VARCHAR, 
	discord_user_id VARCHAR, 
	discord_guild_id VARCHAR, 
	platform VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS tenant_subscriptions (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	plan_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	billing_cycle VARCHAR, 
	current_period_start DATETIME NOT NULL, 
	current_period_end DATETIME NOT NULL, 
	messages_used_current_period INTEGER, 
	integrations_count INTEGER, 
	active_addons TEXT, 
	stripe_subscription_id VARCHAR, 
	stripe_customer_id VARCHAR, 
	status VARCHAR, 
	flutterwave_tx_ref VARCHAR, 
	flutterwave_flw_ref VARCHAR, 
	flutterwave_customer_id VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(plan_id) REFERENCES pricing_plans (id)
);

CREATE TABLE IF NOT EXISTS conversation_sessions (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	user_identifier VARCHAR NOT NULL, 
	platform VARCHAR NOT NULL, 
	started_at DATETIME NOT NULL, 
	last_activity DATETIME NOT NULL, 
	is_active BOOLEAN, 
	message_count INTEGER, 
	duration_minutes INTEGER, 
	counted_for_billing BOOLEAN, 
	billing_period_start DATETIME, 
	extra_data TEXT, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS security_incidents (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	session_id VARCHAR, 
	user_identifier VARCHAR, 
	platform VARCHAR, 
	risk_type VARCHAR(50), 
	user_message TEXT, 
	security_response TEXT, 
	matched_patterns TEXT, 
	severity_score INTEGER, 
	detected_at DATETIME, 
	reviewed BOOLEAN, 
	reviewer_notes TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS agents (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	email VARCHAR NOT NULL, 
	full_name VARCHAR NOT NULL, 
	display_name VARCHAR, 
	avatar_url VARCHAR, 
	password_hash VARCHAR, 
	invite_token VARCHAR, 
	invited_by INTEGER NOT NULL, 
	invited_at DATETIME, 
	password_set_at DATETIME, 
	status VARCHAR, 
	is_active BOOLEAN, 
	last_login DATETIME, 
	last_seen DATETIME, 
	is_online BOOLEAN, 
	total_conversations INTEGER, 
	total_messages_sent INTEGER, 
	average_response_time FLOAT, 
	customer_satisfaction_avg FLOAT, 
	conversations_today INTEGER, 
	notification_settings TEXT, 
	timezone VARCHAR, 
	max_concurrent_chats INTEGER, 
	auto_assign BOOLEAN, 
	work_hours_start VARCHAR, 
	work_hours_end VARCHAR, 
	work_days VARCHAR, 
	created_at DATETIME, 
	updated_at DATETIME, 
	role VARCHAR, 
	promoted_at DATETIME, 
	promoted_by INTEGER, 
	can_assign_conversations BOOLEAN, 
	can_manage_team BOOLEAN, 
	can_access_analytics BOOLEAN, 
	primary_specialization VARCHAR(50), 
	secondary_specializations JSON, 
	skill_level INTEGER, 
	accepts_overflow BOOLEAN, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(invited_by) REFERENCES tenants (id), 
	FOREIGN KEY(promoted_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS live_chat_settings (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	is_enabled BOOLEAN, 
	welcome_message TEXT, 
	offline_message TEXT, 
	pre_chat_form_enabled BOOLEAN, 
	post_chat_survey_enabled BOOLEAN, 
	max_queue_size INTEGER, 
	max_wait_time_minutes INTEGER, 
	queue_timeout_message TEXT, 
	auto_assignment_enabled BOOLEAN, 
	assignment_method VARCHAR, 
	max_chats_per_agent INTEGER, 
	business_hours_enabled BOOLEAN, 
	business_hours TEXT, 
	timezone VARCHAR, 
	email_notifications_enabled BOOLEAN, 
	escalation_email VARCHAR, 
	notification_triggers TEXT, 
	widget_color VARCHAR, 
	widget_position VARCHAR, 
	company_logo_url VARCHAR, 
	file_upload_enabled BOOLEAN, 
	file_size_limit_mb INTEGER, 
	allowed_file_types TEXT, 
	customer_info_retention_days INTEGER, 
	require_email_verification BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (tenant_id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS customer_profiles (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	customer_identifier VARCHAR NOT NULL, 
	first_seen DATETIME, 
	last_seen DATETIME, 
	total_conversations INTEGER, 
	total_sessions INTEGER, 
	preferred_language VARCHAR, 
	time_zone VARCHAR, 
	preferred_contact_method VARCHAR, 
	customer_satisfaction_avg FLOAT, 
	average_session_duration INTEGER, 
	total_messages_sent INTEGER, 
	data_collection_consent BOOLEAN, 
	marketing_consent BOOLEAN, 
	last_consent_update DATETIME, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS instagram_integrations (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	meta_app_id VARCHAR NOT NULL, 
	meta_app_secret VARCHAR NOT NULL, 
	instagram_business_account_id VARCHAR NOT NULL, 
	instagram_username VARCHAR NOT NULL, 
	facebook_page_id VARCHAR NOT NULL, 
	facebook_page_name VARCHAR, 
	page_access_token TEXT NOT NULL, 
	token_expires_at DATETIME, 
	webhook_verify_token VARCHAR NOT NULL, 
	webhook_subscribed BOOLEAN, 
	webhook_subscription_fields JSON, 
	bot_enabled BOOLEAN, 
	bot_status VARCHAR, 
	auto_reply_enabled BOOLEAN, 
	business_verification_required BOOLEAN, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME, 
	last_message_at DATETIME, 
	last_error TEXT, 
	error_count INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS telegram_integrations (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	bot_token VARCHAR NOT NULL, 
	bot_username VARCHAR, 
	bot_name VARCHAR, 
	webhook_url VARCHAR, 
	webhook_secret VARCHAR, 
	is_active BOOLEAN, 
	is_webhook_set BOOLEAN, 
	enable_groups BOOLEAN, 
	enable_privacy_mode BOOLEAN, 
	enable_inline_mode BOOLEAN, 
	welcome_message TEXT, 
	help_message TEXT, 
	enable_typing_indicator BOOLEAN, 
	max_messages_per_minute INTEGER, 
	last_webhook_received DATETIME, 
	last_message_sent DATETIME, 
	total_messages_received INTEGER, 
	total_messages_sent INTEGER, 
	last_error TEXT, 
	error_count INTEGER, 
	last_error_at DATETIME, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME, 
	activated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS password_resets (
	id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	token VARCHAR NOT NULL, 
	expires_at DATETIME NOT NULL, 
	is_used BOOLEAN, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS booking_requests (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	session_id VARCHAR, 
	user_identifier VARCHAR, 
	user_email VARCHAR, 
	user_name VARCHAR, 
	calendly_event_uri VARCHAR, 
	calendly_event_uuid VARCHAR, 
	booking_url VARCHAR, 
	status VARCHAR, 
	booking_message TEXT, 
	created_at DATETIME, 
	booked_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(session_id) REFERENCES chat_sessions (session_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
	id INTEGER NOT NULL, 
	session_id INTEGER, 
	content TEXT, 
	translated_content TEXT, 
	source_language VARCHAR(10), 
	target_language VARCHAR(10), 
	is_from_user BOOLEAN, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(session_id) REFERENCES chat_sessions (id)
);

CREATE TABLE IF NOT EXISTS usage_logs (
	id INTEGER NOT NULL, 
	subscription_id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	usage_type VARCHAR NOT NULL, 
	count INTEGER, 
	integration_type VARCHAR, 
	extra_data TEXT, 
	session_id VARCHAR, 
	user_identifier VARCHAR, 
	platform VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(subscription_id) REFERENCES tenant_subscriptions (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS billing_history (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	subscription_id INTEGER NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	currency VARCHAR, 
	billing_period_start DATETIME NOT NULL, 
	billing_period_end DATETIME NOT NULL, 
	plan_name VARCHAR, 
	conversations_included INTEGER, 
	conversations_used INTEGER, 
	addons_included TEXT, 
	stripe_invoice_id VARCHAR, 
	stripe_charge_id VARCHAR, 
	payment_status VARCHAR, 
	payment_date DATETIME, 
	payment_method VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(subscription_id) REFERENCES tenant_subscriptions (id)
);

CREATE TABLE IF NOT EXISTS pending_feedback (
	id INTEGER NOT NULL, 
	feedback_id VARCHAR, 
	tenant_id INTEGER, 
	session_id VARCHAR, 
	user_email VARCHAR, 
	user_question TEXT, 
	bot_response TEXT, 
	conversation_context TEXT, 
	tenant_email_sent BOOLEAN, 
	tenant_email_id VARCHAR, 
	tenant_response TEXT, 
	user_notified BOOLEAN, 
	user_email_id VARCHAR, 
	form_accessed BOOLEAN, 
	form_accessed_at DATETIME, 
	form_expired BOOLEAN, 
	add_to_faq BOOLEAN, 
	faq_question TEXT, 
	faq_answer TEXT, 
	faq_created BOOLEAN, 
	status VARCHAR, 
	created_at DATETIME, 
	tenant_notified_at DATETIME, 
	resolved_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(session_id) REFERENCES chat_sessions (session_id)
);

CREATE TABLE IF NOT EXISTS live_chat_conversations (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	customer_identifier VARCHAR NOT NULL, 
	customer_email VARCHAR, 
	customer_name VARCHAR, 
	customer_phone VARCHAR, 
	customer_ip VARCHAR, 
	customer_user_agent TEXT, 
	chatbot_session_id VARCHAR, 
	handoff_reason VARCHAR, 
	handoff_trigger VARCHAR, 
	handoff_context TEXT, 
	original_question TEXT, 
	status VARCHAR, 
	queue_position INTEGER, 
	priority_level INTEGER, 
	queue_entry_time DATETIME, 
	assigned_agent_id INTEGER, 
	assigned_at DATETIME, 
	assignment_method VARCHAR, 
	previous_agent_id INTEGER, 
	created_at DATETIME, 
	first_response_at DATETIME, 
	last_activity_at DATETIME, 
	closed_at DATETIME, 
	wait_time_seconds INTEGER, 
	response_time_seconds INTEGER, 
	conversation_duration_seconds INTEGER, 
	message_count INTEGER, 
	agent_message_count INTEGER, 
	customer_message_count INTEGER, 
	customer_satisfaction INTEGER, 
	customer_feedback TEXT, 
	satisfaction_submitted_at DATETIME, 
	closed_by VARCHAR, 
	closure_reason VARCHAR, 
	resolution_status VARCHAR, 
	agent_notes TEXT, 
	internal_notes TEXT, 
	tags TEXT, 
	category VARCHAR, 
	department VARCHAR, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(assigned_agent_id) REFERENCES agents (id), 
	FOREIGN KEY(previous_agent_id) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS agent_sessions (
	id INTEGER NOT NULL, 
	agent_id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	session_id VARCHAR NOT NULL, 
	status VARCHAR, 
	login_at DATETIME, 
	logout_at DATETIME, 
	last_activity DATETIME, 
	active_conversations INTEGER, 
	max_concurrent_chats INTEGER, 
	is_accepting_chats BOOLEAN, 
	messages_sent INTEGER, 
	conversations_handled INTEGER, 
	average_response_time FLOAT, 
	total_online_time INTEGER, 
	ip_address VARCHAR, 
	user_agent VARCHAR, 
	websocket_id VARCHAR, 
	device_type VARCHAR, 
	browser VARCHAR, 
	status_message VARCHAR, 
	away_message VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (websocket_id)
);

CREATE TABLE IF NOT EXISTS conversation_tags (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	name VARCHAR NOT NULL, 
	color VARCHAR, 
	description VARCHAR, 
	usage_count INTEGER, 
	created_by_agent_id INTEGER, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(created_by_agent_id) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS customer_sessions (
	id INTEGER NOT NULL, 
	customer_profile_id INTEGER NOT NULL, 
	session_id VARCHAR NOT NULL, 
	started_at DATETIME, 
	ended_at DATETIME, 
	duration_seconds INTEGER, 
	ip_address VARCHAR, 
	user_agent TEXT, 
	device_fingerprint VARCHAR, 
	country VARCHAR, 
	region VARCHAR, 
	city VARCHAR, 
	page_views INTEGER, 
	conversations_started INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_profile_id) REFERENCES customer_profiles (id), 
	UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS customer_devices (
	id INTEGER NOT NULL, 
	customer_profile_id INTEGER NOT NULL, 
	device_fingerprint VARCHAR NOT NULL, 
	device_type VARCHAR, 
	browser_name VARCHAR, 
	browser_version VARCHAR, 
	operating_system VARCHAR, 
	screen_resolution VARCHAR, 
	supports_websockets BOOLEAN, 
	supports_file_upload BOOLEAN, 
	supports_notifications BOOLEAN, 
	first_seen DATETIME, 
	last_seen DATETIME, 
	total_sessions INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_profile_id) REFERENCES customer_profiles (id)
);

CREATE TABLE IF NOT EXISTS customer_preferences (
	id INTEGER NOT NULL, 
	customer_profile_id INTEGER NOT NULL, 
	preferred_language VARCHAR, 
	preferred_agent_gender VARCHAR, 
	preferred_communication_style VARCHAR, 
	email_notifications BOOLEAN, 
	sms_notifications BOOLEAN, 
	browser_notifications BOOLEAN, 
	requires_accessibility_features BOOLEAN, 
	accessibility_preferences JSON, 
	data_retention_preference VARCHAR, 
	third_party_sharing_consent BOOLEAN, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_profile_id) REFERENCES customer_profiles (id)
);

CREATE TABLE IF NOT EXISTS agent_tags (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	display_name VARCHAR(100) NOT NULL, 
	category VARCHAR(50) NOT NULL, 
	description TEXT, 
	color VARCHAR(7), 
	icon VARCHAR(50), 
	priority_weight FLOAT, 
	is_active BOOLEAN, 
	keywords JSON, 
	routing_rules JSON, 
	total_conversations INTEGER, 
	success_rate FLOAT, 
	average_satisfaction FLOAT, 
	created_by INTEGER, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(created_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS agent_permission_overrides (
	id INTEGER NOT NULL, 
	agent_id INTEGER NOT NULL, 
	permission VARCHAR NOT NULL, 
	granted BOOLEAN, 
	granted_by INTEGER, 
	granted_at DATETIME, 
	reason TEXT, 
	PRIMARY KEY (id), 
	CONSTRAINT unique_agent_permission UNIQUE (agent_id, permission), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(granted_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS agent_role_history (
	id INTEGER NOT NULL, 
	agent_id INTEGER NOT NULL, 
	old_role VARCHAR, 
	new_role VARCHAR NOT NULL, 
	changed_by INTEGER, 
	changed_at DATETIME, 
	reason TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(changed_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS instagram_conversations (
	id INTEGER NOT NULL, 
	integration_id INTEGER, 
	tenant_id INTEGER, 
	instagram_user_id VARCHAR NOT NULL, 
	instagram_username VARCHAR, 
	user_profile_name VARCHAR, 
	user_profile_picture VARCHAR, 
	conversation_id VARCHAR, 
	thread_id VARCHAR, 
	is_active BOOLEAN, 
	conversation_status VARCHAR, 
	conversation_source VARCHAR, 
	initial_message_type VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME, 
	last_message_at DATETIME, 
	last_user_message_at DATETIME, 
	last_bot_message_at DATETIME, 
	total_messages INTEGER, 
	user_messages INTEGER, 
	bot_messages INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(integration_id) REFERENCES instagram_integrations (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS instagram_webhook_events (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	integration_id INTEGER, 
	event_type VARCHAR NOT NULL, 
	event_id VARCHAR, 
	instagram_user_id VARCHAR, 
	processing_status VARCHAR, 
	processing_error TEXT, 
	processed_at DATETIME, 
	raw_payload JSON NOT NULL, 
	headers JSON, 
	received_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	instagram_timestamp DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(integration_id) REFERENCES instagram_integrations (id)
);

CREATE TABLE IF NOT EXISTS telegram_chats (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	telegram_integration_id INTEGER, 
	chat_id VARCHAR NOT NULL, 
	chat_type VARCHAR NOT NULL, 
	user_id VARCHAR, 
	username VARCHAR, 
	first_name VARCHAR, 
	last_name VARCHAR, 
	is_active BOOLEAN, 
	language_code VARCHAR, 
	first_message_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	last_message_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	total_messages INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(telegram_integration_id) REFERENCES telegram_integrations (id)
);

CREATE TABLE IF NOT EXISTS agent_tags_association (
	agent_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	proficiency_level INTEGER, 
	assigned_at DATETIME, 
	assigned_by INTEGER, 
	PRIMARY KEY (agent_id, tag_id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tag_id) REFERENCES agent_tags (id), 
	FOREIGN KEY(assigned_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS live_chat_messages (
	id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	content TEXT NOT NULL, 
	message_type VARCHAR, 
	raw_content TEXT, 
	sender_type VARCHAR NOT NULL, 
	sender_id VARCHAR, 
	agent_id INTEGER, 
	sender_name VARCHAR, 
	sender_avatar VARCHAR, 
	sent_at DATETIME, 
	delivered_at DATETIME, 
	read_at DATETIME, 
	edited_at DATETIME, 
	is_internal BOOLEAN, 
	is_edited BOOLEAN, 
	is_deleted BOOLEAN, 
	deleted_at DATETIME, 
	attachment_url VARCHAR, 
	attachment_name VARCHAR, 
	attachment_type VARCHAR, 
	attachment_size INTEGER, 
	system_event_type VARCHAR, 
	system_event_data TEXT, 
	client_message_id VARCHAR, 
	reply_to_message_id INTEGER, 
	thread_id VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES live_chat_conversations (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(reply_to_message_id) REFERENCES live_chat_messages (id)
);

CREATE TABLE IF NOT EXISTS chat_queue (
	id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	position INTEGER NOT NULL, 
	priority INTEGER, 
	estimated_wait_time INTEGER, 
	preferred_agent_id INTEGER, 
	assignment_criteria TEXT, 
	skills_required TEXT, 
	language_preference VARCHAR, 
	entry_reason VARCHAR, 
	queue_source VARCHAR, 
	queued_at DATETIME, 
	assigned_at DATETIME, 
	removed_at DATETIME, 
	status VARCHAR, 
	abandon_reason VARCHAR, 
	customer_message_preview TEXT, 
	urgency_indicators TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (conversation_id), 
	FOREIGN KEY(conversation_id) REFERENCES live_chat_conversations (id), 
	FOREIGN KEY(preferred_agent_id) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS conversation_transfers (
	id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	from_agent_id INTEGER NOT NULL, 
	to_agent_id INTEGER, 
	transfer_reason VARCHAR, 
	transfer_notes TEXT, 
	status VARCHAR, 
	initiated_at DATETIME, 
	completed_at DATETIME, 
	conversation_summary TEXT, 
	customer_context TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES live_chat_conversations (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(from_agent_id) REFERENCES agents (id), 
	FOREIGN KEY(to_agent_id) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS agent_tag_performance (
	id INTEGER NOT NULL, 
	agent_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	total_conversations INTEGER, 
	successful_resolutions INTEGER, 
	average_resolution_time FLOAT, 
	customer_satisfaction_avg FLOAT, 
	conversations_last_30_days INTEGER, 
	satisfaction_last_30_days FLOAT, 
	proficiency_level INTEGER, 
	improvement_trend FLOAT, 
	certified BOOLEAN, 
	certification_date DATETIME, 
	last_training_date DATETIME, 
	is_available_for_tag BOOLEAN, 
	max_concurrent_for_tag INTEGER, 
	current_active_conversations INTEGER, 
	last_updated DATETIME, 
	last_conversation_date DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tag_id) REFERENCES agent_tags (id)
);

CREATE TABLE IF NOT EXISTS smart_routing_log (
	id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	tenant_id INTEGER NOT NULL, 
	assigned_agent_id INTEGER, 
	routing_method VARCHAR(50) NOT NULL, 
	confidence_score FLOAT, 
	detected_tags JSON, 
	customer_context JSON, 
	available_agents JSON, 
	scoring_breakdown JSON, 
	fallback_reason VARCHAR(200), 
	alternative_agents JSON, 
	customer_satisfaction INTEGER, 
	resolution_time_minutes INTEGER, 
	was_transferred BOOLEAN, 
	transfer_reason VARCHAR(200), 
	routing_accuracy FLOAT, 
	success_factors JSON, 
	improvement_suggestions JSON, 
	routed_at DATETIME, 
	conversation_ended_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES live_chat_conversations (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(assigned_agent_id) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS instagram_messages (
	id INTEGER NOT NULL, 
	conversation_id INTEGER, 
	tenant_id INTEGER, 
	instagram_message_id VARCHAR, 
	message_uuid VARCHAR, 
	message_type VARCHAR, 
	content TEXT, 
	media_url VARCHAR, 
	media_type VARCHAR, 
	media_size INTEGER, 
	is_from_user BOOLEAN, 
	message_status VARCHAR, 
	reply_to_story BOOLEAN, 
	story_id VARCHAR, 
	quick_reply_payload VARCHAR, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	instagram_timestamp DATETIME, 
	delivered_at DATETIME, 
	read_at DATETIME, 
	send_error TEXT, 
	retry_count INTEGER, 
	raw_webhook_data JSON, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES instagram_conversations (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE IF NOT EXISTS conversation_tagging (
	id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL, 
	confidence_score FLOAT, 
	detection_method VARCHAR(50) NOT NULL, 
	detected_keywords JSON, 
	message_text TEXT, 
	message_id INTEGER, 
	influenced_routing BOOLEAN, 
	routing_weight FLOAT, 
	human_verified BOOLEAN, 
	verified_by INTEGER, 
	verified_at DATETIME, 
	detected_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES live_chat_conversations (id), 
	FOREIGN KEY(tag_id) REFERENCES agent_tags (id), 
	FOREIGN KEY(message_id) REFERENCES live_chat_messages (id), 
	FOREIGN KEY(verified_by) REFERENCES agents (id)
);

CREATE TABLE IF NOT EXISTS knowledge_bases (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tenant_id INTEGER NOT NULL,
                name TEXT NOT NULL,
                description TEXT,
                file_path TEXT,
                document_type TEXT NOT NULL,
                vector_store_id TEXT UNIQUE NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP,
                processing_status TEXT DEFAULT 'pending',
                processing_error TEXT,
                processed_at TIMESTAMP,
                base_url TEXT,
                crawl_depth INTEGER DEFAULT 3,
                crawl_frequency_hours INTEGER DEFAULT 24,
                last_crawled_at TIMESTAMP,
                pages_crawled INTEGER DEFAULT 0,
                include_patterns TEXT,
                exclude_patterns TEXT,
                FOREIGN KEY (tenant_id) REFERENCES tenants (id)
            );

CREATE TABLE IF NOT EXISTS scraped_emails (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
            email VARCHAR(254) NOT NULL,
            email_hash VARCHAR(32) UNIQUE NOT NULL,
            source VARCHAR(50) NOT NULL,
            capture_method VARCHAR(50) NOT NULL,
            session_id VARCHAR(255) REFERENCES chat_sessions(session_id) ON DELETE SET NULL,
            user_agent TEXT,
            referrer_url TEXT,
            ip_address VARCHAR(45),
            consent_given BOOLEAN DEFAULT 0 NOT NULL,
            verified BOOLEAN DEFAULT 0 NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
        );

