"""add_tenant_branding

Revision ID: c325e68aab7e
Revises: c972fb4e4f2f
Create Date: 2025-06-20 01:14:16.843354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c325e68aab7e'
down_revision: Union[str, None] = 'c972fb4e4f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_sessions_agent_id', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_status', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_id', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_session_token', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('idx_conversation_tags_name', table_name='conversation_tags')
    op.drop_index('idx_conversation_tags_tenant_id', table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_table('live_chat_settings')
    op.drop_index('idx_pending_feedback_created_at', table_name='pending_feedback')
    op.drop_index('idx_pending_feedback_feedback_id', table_name='pending_feedback')
    op.drop_index('idx_pending_feedback_form_status', table_name='pending_feedback')
    op.drop_index('idx_pending_feedback_tenant_id', table_name='pending_feedback')
    op.drop_index('idx_pending_feedback_user_notified', table_name='pending_feedback')
    op.drop_table('pending_feedback')
    op.drop_index('idx_slack_channel_tenant', table_name='slack_channel_context')
    op.drop_index('ix_slack_channel_context_channel_id', table_name='slack_channel_context')
    op.drop_index('ix_slack_channel_context_id', table_name='slack_channel_context')
    op.drop_index('ix_slack_channel_context_tenant_id', table_name='slack_channel_context')
    op.drop_table('slack_channel_context')
    op.drop_index('ix_usage_logs_id', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index('ix_pricing_plans_id', table_name='pricing_plans')
    op.drop_index('ix_pricing_plans_name', table_name='pricing_plans')
    op.drop_index('ix_pricing_plans_plan_type', table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index('idx_agents_email', table_name='agents')
    op.drop_index('idx_agents_invite_token', table_name='agents')
    op.drop_index('idx_agents_is_online', table_name='agents')
    op.drop_index('idx_agents_status', table_name='agents')
    op.drop_index('idx_agents_tenant_id', table_name='agents')
    op.drop_index('ix_agents_id', table_name='agents')
    op.drop_table('agents')
    op.drop_table('admins_backup')
    op.drop_index('idx_security_incidents_risk_type', table_name='security_incidents')
    op.drop_index('idx_security_incidents_tenant_detected', table_name='security_incidents')
    op.drop_index('ix_security_incidents_id', table_name='security_incidents')
    op.drop_index('ix_security_incidents_user_identifier', table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_index('ix_live_chat_messages_id', table_name='live_chat_messages')
    op.drop_table('live_chat_messages')
    op.drop_index('idx_conversation_transfers_conversation_id', table_name='conversation_transfers')
    op.drop_index('idx_conversation_transfers_from_agent', table_name='conversation_transfers')
    op.drop_index('idx_conversation_transfers_to_agent', table_name='conversation_transfers')
    op.drop_table('conversation_transfers')
    op.drop_index('idx_chat_queue_position', table_name='chat_queue')
    op.drop_index('idx_chat_queue_priority', table_name='chat_queue')
    op.drop_index('idx_chat_queue_tenant_id', table_name='chat_queue')
    op.drop_index('ix_chat_queue_id', table_name='chat_queue')
    op.drop_table('chat_queue')
    op.drop_index('ix_live_chats_id', table_name='live_chats')
    op.drop_index('ix_live_chats_session_id', table_name='live_chats')
    op.drop_index('ix_live_chats_user_identifier', table_name='live_chats')
    op.drop_table('live_chats')
    op.drop_index('ix_tenant_subscriptions_id', table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index('idx_slack_thread_tenant_channel', table_name='slack_thread_memory')
    op.drop_index('idx_slack_thread_ts', table_name='slack_thread_memory')
    op.drop_index('idx_slack_thread_user_activity', table_name='slack_thread_memory')
    op.drop_index('ix_slack_thread_memory_channel_id', table_name='slack_thread_memory')
    op.drop_index('ix_slack_thread_memory_id', table_name='slack_thread_memory')
    op.drop_index('ix_slack_thread_memory_tenant_id', table_name='slack_thread_memory')
    op.drop_index('ix_slack_thread_memory_thread_ts', table_name='slack_thread_memory')
    op.drop_index('ix_slack_thread_memory_user_id', table_name='slack_thread_memory')
    op.drop_table('slack_thread_memory')
    op.drop_index('ix_conversations_customer_id', table_name='conversations')
    op.drop_index('ix_conversations_session_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_conversation_sessions_activity', table_name='conversation_sessions')
    op.drop_index('idx_conversation_sessions_billing', table_name='conversation_sessions')
    op.drop_index('idx_conversation_sessions_tenant_user', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_table('admins')
    op.drop_index('ix_billing_history_id', table_name='billing_history')
    op.drop_table('billing_history')
    op.drop_table('messages')
    op.drop_index('idx_live_chat_conversations_assigned_agent', table_name='live_chat_conversations')
    op.drop_index('idx_live_chat_conversations_chatbot_session', table_name='live_chat_conversations')
    op.drop_index('idx_live_chat_conversations_created_at', table_name='live_chat_conversations')
    op.drop_index('idx_live_chat_conversations_customer_id', table_name='live_chat_conversations')
    op.drop_index('idx_live_chat_conversations_status', table_name='live_chat_conversations')
    op.drop_index('idx_live_chat_conversations_tenant_id', table_name='live_chat_conversations')
    op.drop_table('live_chat_conversations')
    op.alter_column('chat_sessions', 'email_captured_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'email_expires_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'processing_status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('knowledge_bases', 'processed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_knowledge_bases_processing_status', table_name='knowledge_bases')
    op.alter_column('tenants', 'business_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('tenants', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.create_index(op.f('ix_tenants_business_name'), 'tenants', ['business_name'], unique=False)
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_supabase_user_id'), 'tenants', ['supabase_user_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'tenants', ['impersonating_tenant_id'], ['id'])
    op.drop_column('tenants', 'contact_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('contact_email', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_supabase_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_business_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.alter_column('tenants', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tenants', 'business_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.create_index('idx_knowledge_bases_processing_status', 'knowledge_bases', ['processing_status'], unique=False)
    op.alter_column('knowledge_bases', 'processed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'processing_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('chat_sessions', 'email_expires_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'email_captured_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('live_chat_conversations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_identifier', sa.VARCHAR(), nullable=False),
    sa.Column('customer_email', sa.VARCHAR(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(), nullable=True),
    sa.Column('customer_ip', sa.VARCHAR(), nullable=True),
    sa.Column('customer_user_agent', sa.TEXT(), nullable=True),
    sa.Column('chatbot_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('handoff_reason', sa.VARCHAR(), nullable=True),
    sa.Column('handoff_trigger', sa.VARCHAR(), nullable=True),
    sa.Column('handoff_context', sa.TEXT(), nullable=True),
    sa.Column('original_question', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('queue_position', sa.INTEGER(), nullable=True),
    sa.Column('priority_level', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('queue_entry_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('assigned_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.Column('assignment_method', sa.VARCHAR(), nullable=True),
    sa.Column('previous_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('first_response_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('wait_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('response_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('conversation_duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('agent_message_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('customer_message_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('customer_satisfaction', sa.INTEGER(), nullable=True),
    sa.Column('customer_feedback', sa.TEXT(), nullable=True),
    sa.Column('satisfaction_submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_by', sa.VARCHAR(), nullable=True),
    sa.Column('closure_reason', sa.VARCHAR(), nullable=True),
    sa.Column('resolution_status', sa.VARCHAR(), nullable=True),
    sa.Column('agent_notes', sa.TEXT(), nullable=True),
    sa.Column('internal_notes', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['previous_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_chat_conversations_tenant_id', 'live_chat_conversations', ['tenant_id'], unique=False)
    op.create_index('idx_live_chat_conversations_status', 'live_chat_conversations', ['status'], unique=False)
    op.create_index('idx_live_chat_conversations_customer_id', 'live_chat_conversations', ['customer_identifier'], unique=False)
    op.create_index('idx_live_chat_conversations_created_at', 'live_chat_conversations', ['created_at'], unique=False)
    op.create_index('idx_live_chat_conversations_chatbot_session', 'live_chat_conversations', ['chatbot_session_id'], unique=False)
    op.create_index('idx_live_chat_conversations_assigned_agent', 'live_chat_conversations', ['assigned_agent_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=7), nullable=True),
    sa.Column('from_agent', sa.BOOLEAN(), nullable=True),
    sa.Column('sender_name', sa.VARCHAR(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('billing_period_start', sa.DATETIME(), nullable=False),
    sa.Column('billing_period_end', sa.DATETIME(), nullable=False),
    sa.Column('stripe_invoice_id', sa.VARCHAR(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('plan_name', sa.TEXT(), nullable=True),
    sa.Column('conversations_included', sa.INTEGER(), nullable=True),
    sa.Column('conversations_used', sa.INTEGER(), nullable=True),
    sa.Column('addons_included', sa.TEXT(), nullable=True),
    sa.Column('stripe_charge_id', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_history_id', 'billing_history', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('user_identifier', sa.TEXT(), nullable=False),
    sa.Column('platform', sa.TEXT(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_activity', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('counted_for_billing', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('billing_period_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('extra_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_sessions_tenant_user', 'conversation_sessions', ['tenant_id', 'user_identifier'], unique=False)
    op.create_index('idx_conversation_sessions_billing', 'conversation_sessions', ['tenant_id', 'counted_for_billing'], unique=False)
    op.create_index('idx_conversation_sessions_activity', 'conversation_sessions', ['last_activity'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), nullable=True),
    sa.Column('customer_email', sa.VARCHAR(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('bot_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('handoff_reason', sa.TEXT(), nullable=True),
    sa.Column('bot_context', sa.TEXT(), nullable=True),
    sa.Column('queue_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('first_response_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('resolution_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('satisfaction_rating', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_session_id', 'conversations', ['session_id'], unique=1)
    op.create_index('ix_conversations_customer_id', 'conversations', ['customer_id'], unique=False)
    op.create_table('slack_thread_memory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('thread_ts', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('conversation_context', sa.TEXT(), nullable=True),
    sa.Column('user_preferences', sa.TEXT(), nullable=True),
    sa.Column('topic_summary', sa.TEXT(), nullable=True),
    sa.Column('message_count', sa.INTEGER(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slack_thread_memory_user_id', 'slack_thread_memory', ['user_id'], unique=False)
    op.create_index('ix_slack_thread_memory_thread_ts', 'slack_thread_memory', ['thread_ts'], unique=False)
    op.create_index('ix_slack_thread_memory_tenant_id', 'slack_thread_memory', ['tenant_id'], unique=False)
    op.create_index('ix_slack_thread_memory_id', 'slack_thread_memory', ['id'], unique=False)
    op.create_index('ix_slack_thread_memory_channel_id', 'slack_thread_memory', ['channel_id'], unique=False)
    op.create_index('idx_slack_thread_user_activity', 'slack_thread_memory', ['user_id', 'last_activity'], unique=False)
    op.create_index('idx_slack_thread_ts', 'slack_thread_memory', ['thread_ts'], unique=False)
    op.create_index('idx_slack_thread_tenant_channel', 'slack_thread_memory', ['tenant_id', 'channel_id'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('billing_cycle', sa.VARCHAR(), nullable=True),
    sa.Column('current_period_start', sa.DATETIME(), nullable=False),
    sa.Column('current_period_end', sa.DATETIME(), nullable=False),
    sa.Column('messages_used_current_period', sa.INTEGER(), nullable=True),
    sa.Column('integrations_count', sa.INTEGER(), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('active_addons', sa.TEXT(), nullable=True),
    sa.Column('stripe_customer_id', sa.TEXT(), nullable=True),
    sa.Column('flutterwave_tx_ref', sa.TEXT(), nullable=True),
    sa.Column('flutterwave_flw_ref', sa.TEXT(), nullable=True),
    sa.Column('flutterwave_customer_id', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_subscriptions_id', 'tenant_subscriptions', ['id'], unique=False)
    op.create_table('live_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('user_identifier', sa.VARCHAR(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('chatbot_session_id', sa.VARCHAR(), nullable=True),
    sa.Column('handoff_reason', sa.TEXT(), nullable=True),
    sa.Column('bot_context', sa.TEXT(), nullable=True),
    sa.Column('queue_time', sa.INTEGER(), nullable=True),
    sa.Column('first_response_time', sa.INTEGER(), nullable=True),
    sa.Column('resolution_time', sa.INTEGER(), nullable=True),
    sa.Column('customer_satisfaction', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_chats_user_identifier', 'live_chats', ['user_identifier'], unique=False)
    op.create_index('ix_live_chats_session_id', 'live_chats', ['session_id'], unique=1)
    op.create_index('ix_live_chats_id', 'live_chats', ['id'], unique=False)
    op.create_table('chat_queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('estimated_wait_time', sa.INTEGER(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('required_skills', sa.TEXT(), nullable=True),
    sa.Column('queued_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['live_chats.id'], ),
    sa.ForeignKeyConstraint(['preferred_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index('ix_chat_queue_id', 'chat_queue', ['id'], unique=False)
    op.create_index('idx_chat_queue_tenant_id', 'chat_queue', ['tenant_id'], unique=False)
    op.create_index('idx_chat_queue_priority', 'chat_queue', ['priority'], unique=False)
    op.create_index('idx_chat_queue_position', 'chat_queue', ['position'], unique=False)
    op.create_table('conversation_transfers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('from_agent_id', sa.INTEGER(), nullable=False),
    sa.Column('to_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('transfer_reason', sa.VARCHAR(), nullable=True),
    sa.Column('transfer_notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('initiated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('conversation_summary', sa.TEXT(), nullable=True),
    sa.Column('customer_context', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['live_chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_transfers_to_agent', 'conversation_transfers', ['to_agent_id'], unique=False)
    op.create_index('idx_conversation_transfers_from_agent', 'conversation_transfers', ['from_agent_id'], unique=False)
    op.create_index('idx_conversation_transfers_conversation_id', 'conversation_transfers', ['conversation_id'], unique=False)
    op.create_table('live_chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=7), nullable=True),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_from_user', sa.BOOLEAN(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('sender_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_internal', sa.BOOLEAN(), nullable=True),
    sa.Column('read_by_user', sa.BOOLEAN(), nullable=True),
    sa.Column('read_by_agent', sa.BOOLEAN(), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('platform_message_id', sa.VARCHAR(), nullable=True),
    sa.Column('platform_metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['live_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_chat_messages_id', 'live_chat_messages', ['id'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_identifier', sa.VARCHAR(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('risk_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_message', sa.TEXT(), nullable=True),
    sa.Column('security_response', sa.TEXT(), nullable=True),
    sa.Column('matched_patterns', sa.TEXT(), nullable=True),
    sa.Column('severity_score', sa.INTEGER(), nullable=True),
    sa.Column('detected_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed', sa.BOOLEAN(), nullable=True),
    sa.Column('reviewer_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_incidents_user_identifier', 'security_incidents', ['user_identifier'], unique=False)
    op.create_index('ix_security_incidents_id', 'security_incidents', ['id'], unique=False)
    op.create_index('idx_security_incidents_tenant_detected', 'security_incidents', ['tenant_id', 'detected_at'], unique=False)
    op.create_index('idx_security_incidents_risk_type', 'security_incidents', ['risk_type'], unique=False)
    op.create_table('admins_backup',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('hashed_password', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('skills', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('max_concurrent_chats', sa.INTEGER(), nullable=True),
    sa.Column('current_chat_count', sa.INTEGER(), nullable=True),
    sa.Column('total_chats_handled', sa.INTEGER(), nullable=True),
    sa.Column('average_response_time', sa.INTEGER(), nullable=True),
    sa.Column('customer_satisfaction_rating', sa.FLOAT(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('total_conversations', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_response_time_seconds', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('display_name', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('invite_token', sa.VARCHAR(), nullable=True),
    sa.Column('invited_by', sa.INTEGER(), nullable=True),
    sa.Column('invited_at', sa.DATETIME(), nullable=True),
    sa.Column('password_set_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_online', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_messages_sent', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('customer_satisfaction_avg', sa.REAL(), nullable=True),
    sa.Column('conversations_today', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('notification_settings', sa.TEXT(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), server_default=sa.text("'UTC'"), nullable=True),
    sa.Column('auto_assign', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('work_hours_start', sa.VARCHAR(), nullable=True),
    sa.Column('work_hours_end', sa.VARCHAR(), nullable=True),
    sa.Column('work_days', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_id', 'agents', ['id'], unique=False)
    op.create_index('idx_agents_tenant_id', 'agents', ['tenant_id'], unique=False)
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index('idx_agents_is_online', 'agents', ['is_online'], unique=False)
    op.create_index('idx_agents_invite_token', 'agents', ['invite_token'], unique=False)
    op.create_index('idx_agents_email', 'agents', ['email'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(), nullable=True),
    sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('price_yearly', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_integrations', sa.INTEGER(), nullable=True),
    sa.Column('max_messages_monthly', sa.INTEGER(), nullable=True),
    sa.Column('custom_prompt_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('website_api_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('slack_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('discord_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('whatsapp_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_addon', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_plans_plan_type', 'pricing_plans', ['plan_type'], unique=False)
    op.create_index('ix_pricing_plans_name', 'pricing_plans', ['name'], unique=1)
    op.create_index('ix_pricing_plans_id', 'pricing_plans', ['id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('usage_type', sa.VARCHAR(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('integration_type', sa.VARCHAR(), nullable=True),
    sa.Column('extra_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('user_identifier', sa.TEXT(), nullable=True),
    sa.Column('platform', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_logs_id', 'usage_logs', ['id'], unique=False)
    op.create_table('slack_channel_context',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('channel_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bot_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('thread_mode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('channel_topic', sa.TEXT(), nullable=True),
    sa.Column('common_questions', sa.TEXT(), nullable=True),
    sa.Column('channel_personality', sa.TEXT(), nullable=True),
    sa.Column('total_messages', sa.INTEGER(), nullable=True),
    sa.Column('active_threads', sa.INTEGER(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slack_channel_context_tenant_id', 'slack_channel_context', ['tenant_id'], unique=False)
    op.create_index('ix_slack_channel_context_id', 'slack_channel_context', ['id'], unique=False)
    op.create_index('ix_slack_channel_context_channel_id', 'slack_channel_context', ['channel_id'], unique=False)
    op.create_index('idx_slack_channel_tenant', 'slack_channel_context', ['tenant_id', 'channel_id'], unique=False)
    op.create_table('pending_feedback',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('feedback_id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('user_question', sa.TEXT(), nullable=True),
    sa.Column('bot_response', sa.TEXT(), nullable=True),
    sa.Column('conversation_context', sa.TEXT(), nullable=True),
    sa.Column('tenant_email_sent', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('tenant_response', sa.TEXT(), nullable=True),
    sa.Column('user_notified', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('tenant_email_id', sa.TEXT(), nullable=True),
    sa.Column('user_email_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('tenant_notified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('form_accessed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('form_accessed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('form_expired', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('add_to_faq', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('faq_created', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('faq_question', sa.TEXT(), nullable=True),
    sa.Column('faq_answer', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    op.create_index('idx_pending_feedback_user_notified', 'pending_feedback', ['user_notified'], unique=False)
    op.create_index('idx_pending_feedback_tenant_id', 'pending_feedback', ['tenant_id'], unique=False)
    op.create_index('idx_pending_feedback_form_status', 'pending_feedback', ['feedback_id', 'form_expired', 'form_accessed'], unique=False)
    op.create_index('idx_pending_feedback_feedback_id', 'pending_feedback', ['feedback_id'], unique=False)
    op.create_index('idx_pending_feedback_created_at', 'pending_feedback', ['created_at'], unique=False)
    op.create_table('live_chat_settings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('welcome_message', sa.TEXT(), nullable=True),
    sa.Column('offline_message', sa.TEXT(), nullable=True),
    sa.Column('pre_chat_form_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('post_chat_survey_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_queue_size', sa.INTEGER(), server_default=sa.text('(50)'), nullable=False),
    sa.Column('max_wait_time_minutes', sa.INTEGER(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('queue_timeout_message', sa.TEXT(), nullable=True),
    sa.Column('auto_assignment_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('assignment_method', sa.VARCHAR(), server_default=sa.text("'round_robin'"), nullable=False),
    sa.Column('max_chats_per_agent', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('business_hours_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('business_hours', sa.TEXT(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('email_notifications_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('escalation_email', sa.VARCHAR(), nullable=True),
    sa.Column('notification_triggers', sa.TEXT(), nullable=True),
    sa.Column('widget_color', sa.VARCHAR(), server_default=sa.text("'#6d28d9'"), nullable=False),
    sa.Column('widget_position', sa.VARCHAR(), server_default=sa.text("'bottom-right'"), nullable=False),
    sa.Column('company_logo_url', sa.VARCHAR(), nullable=True),
    sa.Column('file_upload_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('file_size_limit_mb', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('allowed_file_types', sa.TEXT(), nullable=True),
    sa.Column('customer_info_retention_days', sa.INTEGER(), server_default=sa.text('(365)'), nullable=False),
    sa.Column('require_email_verification', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('conversation_tags',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_tags_tenant_id', 'conversation_tags', ['tenant_id'], unique=False)
    op.create_index('idx_conversation_tags_name', 'conversation_tags', ['name'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('session_token', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('logged_in_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('logged_out_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_session_token', 'agent_sessions', ['session_token'], unique=1)
    op.create_index('ix_agent_sessions_id', 'agent_sessions', ['id'], unique=False)
    op.create_index('idx_agent_sessions_status', 'agent_sessions', ['status'], unique=False)
    op.create_index('idx_agent_sessions_agent_id', 'agent_sessions', ['agent_id'], unique=False)
    # ### end Alembic commands ###
